#include <Flash/Mpp/MPPTaskId.h>
#include <fmt/core.h>

namespace DB
{
<<<<<<< HEAD
=======
bool isOldVersion(const MPPQueryId & mpp_query_id)
{
    return mpp_query_id.query_ts == 0 && mpp_query_id.local_query_id == 0 && mpp_query_id.server_id == 0;
}


bool MPPQueryId::operator<(const MPPQueryId & mpp_query_id) const
{
    // compare with MPP query generated by TiDB that version less than v6.6
    bool left_old_version = isOldVersion(*this);
    bool right_old_version = isOldVersion(mpp_query_id);
    if (unlikely(left_old_version && right_old_version))
    {
        return start_ts < mpp_query_id.start_ts;
    }
    if (unlikely(left_old_version))
    {
        return true;
    }
    if (unlikely(right_old_version))
    {
        return false;
    }
    // compare with MPP query generated by TiDB that version after v6.6
    if (query_ts != mpp_query_id.query_ts)
    {
        return query_ts < mpp_query_id.query_ts;
    }
    if (server_id == mpp_query_id.server_id)
    {
        return local_query_id < mpp_query_id.local_query_id;
    }
    // now we can't compare reasonably, just choose one randomly by hash.
    auto lhash = MPPQueryIdHash()(*this);
    auto rhash = MPPQueryIdHash()(mpp_query_id);
    if (lhash != rhash)
    {
        return lhash < rhash;
    }
    // hash values are same, just compare the rest fields.
    if (local_query_id != mpp_query_id.local_query_id)
    {
        return local_query_id < mpp_query_id.local_query_id;
    }
    return server_id < mpp_query_id.server_id;
}
bool MPPQueryId::operator==(const MPPQueryId & rid) const
{
    return query_ts == rid.query_ts && local_query_id == rid.local_query_id && server_id == rid.server_id && start_ts == rid.start_ts;
}
bool MPPQueryId::operator!=(const MPPQueryId & rid) const
{
    return !(*this == rid);
}
bool MPPQueryId::operator<=(const MPPQueryId & rid) const
{
    return *this < rid || *this == rid;
}

size_t MPPQueryIdHash::operator()(MPPQueryId const & mpp_query_id) const noexcept
{
    if (unlikely(isOldVersion(mpp_query_id)))
    {
        return std::hash<UInt64>()(mpp_query_id.start_ts);
    }
    return std::hash<UInt64>()(mpp_query_id.query_ts) ^ std::hash<UInt64>()(mpp_query_id.local_query_id) ^ std::hash<UInt64>()(mpp_query_id.server_id);
}

bool MPPGatherId::operator==(const MPPGatherId & rid) const
{
    return gather_id == rid.gather_id && query_id == rid.query_id;
}

size_t MPPGatherIdHash::operator()(MPPGatherId const & mpp_gather_id) const noexcept
{
    return MPPQueryIdHash()(mpp_gather_id.query_id) ^ std::hash<UInt64>()(mpp_gather_id.gather_id);
}

>>>>>>> 12435a7c05 (Fix "lost cancel" for mpp query (#7589))
String MPPTaskId::toString() const
{
    return isUnknown() ? "<query:N/A,task:N/A>" : fmt::format("<query:{},task:{}>", start_ts, task_id);
}

const MPPTaskId MPPTaskId::unknown_mpp_task_id = MPPTaskId{};

bool operator==(const MPPTaskId & lid, const MPPTaskId & rid)
{
    return lid.start_ts == rid.start_ts && lid.task_id == rid.task_id;
}
} // namespace DB