FROM ubuntu:18.04

WORKDIR /
ENV TZ Asia/Shanghai
ENV LD_LIBRARY_PATH /tics

RUN apt update && apt install -y tzdata python && rm -rf /var/lib/apt/lists/*
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
