FROM ubuntu:17.10

RUN apt update && \
    apt install -y tzdata python

COPY tics /tics

ENV TZ Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /

ENV LD_LIBRARY_PATH /tics

ENTRYPOINT ["/tics/theflash", "server"]
