# Copyright 2026 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM quay.io/rockylinux/rockylinux:8.10.20240528-ubi

USER root
WORKDIR /root/

ENV HOME /root/
ENV TZ Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY tiflash /tiflash
COPY tiflash-columnar /tiflash-columnar
COPY dockerfiles/tiflash-next-gen-entrypoint.sh /usr/local/bin/tiflash-next-gen-entrypoint.sh
RUN chmod +x /usr/local/bin/tiflash-next-gen-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/tiflash-next-gen-entrypoint.sh"]
