[target.x86_64-unknown-linux-gnu]
linker = "/usr/local/bin/clang-15"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld"
]

[target.aarch64-unknown-linux-gnu]
linker = "/usr/local/bin/clang-15"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld", "-C", "link-arg=-Wl,-Bsymbolic"
]

[profile.release]
rpath = true
