set(DIVIDE_INCLUDE_DIR ${TIFLASH_SOURCE_DIR}/contrib/libdivide)
set(CITYHASH_CONTRIB_INCLUDE_DIR ${TIFLASH_SOURCE_DIR}/contrib/libcityhash/include)
set(COMMON_INCLUDE_DIR ${TIFLASH_SOURCE_DIR}/libs/libcommon/include ${TIFLASH_BINARY_DIR}/libs/libcommon/include)
set(DBMS_INCLUDE_DIR ${TIFLASH_SOURCE_DIR}/dbms/src ${TIFLASH_BINARY_DIR}/dbms/src)
set(DOUBLE_CONVERSION_CONTRIB_INCLUDE_DIR ${TIFLASH_SOURCE_DIR}/contrib/double-conversion)
set(PCG_RANDOM_INCLUDE_DIR ${TIFLASH_SOURCE_DIR}/contrib/libpcg-random/include)
