FROM ubuntu:16.04

USER root
WORKDIR /root/

ENV HOME /root/
ENV TZ Asia/Shanghai
ENV LD_LIBRARY_PATH /tiflash

RUN apt update && apt install -y tzdata python && rm -rf /var/lib/apt/lists/*
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY tiflash /tiflash

ENTRYPOINT ["/tiflash/theflash", "server"]
