FROM hub.pingcap.net/jenkins/centos7_golang-1.12

USER root
WORKDIR /root/

ENV HOME /root/
ENV LIBRARY_PATH ""
ENV LD_LIBRARY_PATH ""

COPY prepare-environments /prepare-environments

RUN yum remove -y epel-release

RUN yum makecache \
  && yum install -y \
         ccache \
         devscripts \
         fakeroot \
         debhelper \
         libtool \
         ncurses-static \
         libtool-ltdl-devel \
         python3-devel \
         bzip2 \
         chrpath \
  && curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain nightly  \
  && pip3 install \
          pybind11 \
          pyinstaller \
          dnspython \
          uri \
          requests \
          urllib3 \
          toml \
          setuptools \
          etcd3 \
  && cd /prepare-environments \
  && ./install-cmake.sh \
  && ./install-gcc.sh \
  && ./install-openssl.sh \
  && ./install-libcurl.sh \
  && ./install-grpc.sh \
  && yum remove openssl-devel \
  && yum clean all
