FROM hub.pingcap.net/jenkins/centos7_golang-1.12

USER root
WORKDIR /root/

ENV HOME /root/

COPY prepare-environments /prepare-environments

RUN yum makecache \
  && yum install -y \
         ccache \
         devscripts \
         fakeroot \
         debhelper \
         libtool \
         ncurses-static \
         readline-devel \
         unixODBC-devel \
         openssl-devel \
         libicu-devel \
         libtool-ltdl-devel \
         python3-devel \
  && curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain nightly  \
  && pip3 install \
          pybind11 \
          pyinstaller \
          dnspython \
          uri \
          requests \
          urllib3 \
          toml \
          setuptools \
  && cd /prepare-environments \
  && ./install-openssl.sh \
  && ./install-mysql-dev.sh \
  && ./install-cmake.sh \
  && ./install-gcc.sh \
  && ./install-llvm.sh \
  && ./install-grpc.sh \
  && yum clean all
